# Generated by Django 6.0.6 on 2026-07-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0006_result_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultdetail",
            name="hint_count",
            field=models.IntegerField(default=0),
        ),
    ]
